import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import FormInputs from '../components/FormInputs'
import Button from '../components/Button'


const FORM_INPUTS = [
  {
    label: 'Name',
    name: 'name',
    placeholder: 'Enter your name',
    type: 'text',
    autoComplete: 'on',
  },
  {
    label: 'Email',
    name: 'email',
    placeholder: 'Enter your email',
    type: 'email',
    autoComplete: 'on',
}
]
const Home: NextPage = () =>
{
  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) =>
  { 
    e.preventDefault()
    console.log('Form submitted')
    // e.target.reset()
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>AIROL Summer Camp 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className='text-4xl font-sans font-black text-center mb-2'>Welcome to AIROL Summer Camp 2022</h1>
        <div>
          <form className='w-64 flex flex-col my-2 gap-2' onSubmit={handleSubmit}>
            <p>Kindly provide your details</p>
            {FORM_INPUTS.map((input) => (<FormInputs key={input.name} {...input} />))}
            <Button text='Submit' type='submit'/>

          </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
         Powered by{' '}
          Artificial Intelligence and Robotics Laboratory (AIROL)
        </a>
      </footer>
    </div>
  )
}

export default Home
